# Generated by Django 4.0.5 on 2022-06-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('piva', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cod_fiscale', models.CharField(max_length=16)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('last_name2', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XMLUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xmlfiles')),
                ('name', models.CharField(max_length=40)),
                ('datetime_uploaded', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('piva', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cod_fiscale', models.CharField(max_length=16)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_cond', models.CharField(choices=[('NCON', 'Non Indicato'), ('TP01', 'TP01 - Pagamento Rate'), ('TP02', 'TP02 - Pagamento effettuato'), ('TP03', 'TP03 - Pagamento Anticipato')], max_length=4)),
                ('payment_mod', models.CharField(choices=[('MP01', 'MP01 - contanti'), ('MP02', 'MP02 - assegno'), ('MP03', 'MP03 - assegno circolare'), ('MP04', 'MP04 - contanti presso Tesoreria'), ('MP05', 'MP05 - bonifico'), ('MP06', 'MP06 - vaglia cambiario'), ('MP07', 'MP07 - bollettino bancario'), ('MP08', 'MP08 - carta di pagamento'), ('MP09', 'MP09 - RID'), ('MP10', 'MP10 - RID utenze'), ('MP11', 'MP11 - RID veloce'), ('MP12', 'MP12 - RIBA'), ('MP13', 'MP13 - MAV'), ('MP14', 'MP14 - quietanza erario'), ('MP15', 'MP15 - giroconto su conti di contabilità speciale'), ('MP16', 'MP16 - domiciliazione bancaria'), ('MP17', 'MP17 - domiciliazione postale'), ('MP18', 'MP18 - bollettino di c/c postale'), ('MP19', 'MP19 - SEPA Direct Debit'), ('MP20', 'MP20 - SEPA Direct Debit CORE'), ('MP21', 'MP21 - SEPA Direct Debit B2B'), ('MP22', 'MP22 - Trattenuta su somme già riscosse')], max_length=4)),
                ('date_invoice', models.DateField()),
                ('payment_days', models.IntegerField()),
                ('date_payment', models.DateField()),
                ('amount_invoice', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cashflow.client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cashflow.supplier')),
            ],
            options={
                'ordering': ['date_invoice', 'date_payment'],
            },
        ),
    ]
