# Generated by Django 4.0.5 on 2022-06-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_remove_client_last_name2_remove_xmlupload_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='seller',
            new_name='supplier',
        ),
    ]
