# Generated by Django 4.0.5 on 2022-06-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_rename_seller_invoice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cashflow.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_days',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cashflow.supplier'),
        ),
    ]
