# Generated by Django 4.0.5 on 2022-06-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_invoice_doc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlupload',
            name='name',
            field=models.CharField(default='test.xml', max_length=20),
        ),
    ]
