# Generated by Django 4.0.5 on 2022-07-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_alter_invoice_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlupload',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xml_upload', to='cashflow.invoice'),
        ),
    ]
